name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby-version: ['2.7', '3.0', '3.1', '3.2']

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Ruby ${{ matrix.ruby-version }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true

    - name: Make executable
      run: chmod +x exe/sales_tax_calculator

    - name: Run tests
      run: bundle exec rake test

    - name: Test CLI examples
      run: |
        echo "Testing CLI with sample data..."
        ruby exe/sales_tax_calculator test_data/input1.txt
        ruby exe/sales_tax_calculator test_data/input2.txt
        ruby exe/sales_tax_calculator test_data/input3.txt
        echo "OK!"
