name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    strategy:
      matrix:
        ruby-version: ['ruby']

    env:
      MIN_RUBY: '3.3.4'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Ruby ${{ matrix.ruby-version }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true

    - name: Enforce Ruby >= ${{ env.MIN_RUBY }}
      run: |
        ruby -v
        ruby -e 'require "rubygems"; min = ENV["MIN_RUBY"]; v = Gem::Version.new(RUBY_VERSION); abort("Ruby #{v} is not >= #{min}") unless v >= Gem::Version.new(min); puts "Ruby #{v} OK (>= #{min})"'

    - name: Make executable
      run: chmod +x exe/sales_tax_calculator

    - name: Run tests
      run: bundle exec rake test

    - name: Test CLI examples
      run: |
        echo "Testing CLI with sample data..."
        ruby exe/sales_tax_calculator test_data/input1.txt
        ruby exe/sales_tax_calculator test_data/input2.txt
        ruby exe/sales_tax_calculator test_data/input3.txt
        echo "OK!"
